# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00a789f788bf76fab8acf9ec3710f38aee8b048d2de830ed297b48b4e0a8fa256fd495ed601cf1f79ab4a6b5b358c4c699077cf2ba624a719b14cfb5f579695b

test:
  secret_key_base: c3207d87b6428b77a319123f6cb61c7db9e706b81102be611ee3a15da232ab15ad127bec12d489ebceb8cc6edbec19e40c16ec5dea23c652d403166cdfea344a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
